/*
You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. 
Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''
*/

import java.util.Scanner;
import java.util.Arrays;

class SpotTheDiff{

	static char diffChar(String s, String t){
		if(s.length() == t.length())
			return ' ';
		char sArr[] = s.toCharArray();
		char tArr[] = t.toCharArray();
		Arrays.sort(sArr);
		Arrays.sort(tArr);
		
		for(int i = 0; i < s.length(); i++){
			if(sArr[i] != tArr[i])	
				return tArr[i];			
		}
		return tArr[tArr.length - 1];
	}
	
	public static void main(String ar[]){
		Scanner sc = new Scanner(System.in);
		System.out.print("Enter 2 strings: ");
		String s = sc.next();
		String t = sc.next();
		sc.close();
		System.out.println("'" + diffChar(s, t) + "'");
	}
}
